[QoL]
; Always show unit health bars overhead at all times
; 1 = Enabled | 0 = Disabled
AlwaysOnHealthBars = 1

; Enables native 1920x1080 (Full HD Widescreen) and dynamic FOV
; 1 = Enabled | 0 = Disabled
Enable1080pAndFOV = 1

; Field of View (FOV) in degrees for in-game matches (default: 60)
; Menus and loading screen automatically preserve 45 to keep elements perfectly aligned
FOV = 60
